options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Install Python dependencies
  - name: python:3.11
    id: Install Dependencies
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt

  # Step 2: Optional Lint Check
  - name: python:3.11
    id: Lint Check
    entrypoint: bash
    args: ['-c', 'echo "Linting..."; flake8 || echo "Lint warnings, continuing..."']

  # Step 3: Confirm Flask App Setup
  - name: python:3.11
    id: Confirm Setup
    entrypoint: bash
    args: ['-c', 'echo "✅ Flask backend setup validated in Cloud Build"']

  # Step 4: Build and push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Build and Push Image
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/askdoc-backend',
        '.'
      ]

  - name: gcr.io/cloud-builders/docker
    id: Push Image
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/askdoc-backend'
      ]

  # Step 5: Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy to Cloud Run
    args:
      [
        'run',
        'deploy',
        'askdoc-backend',
        '--image',
        'gcr.io/$PROJECT_ID/askdoc-backend',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/askdoc-backend
