steps:
  # Step 1: Install Python dependencies
  - name: 'python:3.11'
    id: Install Dependencies
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # Step 2: Lint check (optional)
  - name: 'python:3.11'
    id: Lint Check
    entrypoint: bash
    args:
      - -c
      - |
        echo "Linting..."
        flake8 || echo "Lint warnings, continuing..."

  # Step 3: Confirm setup
  - name: 'python:3.11'
    id: Confirm Setup
    entrypoint: bash
    args: ['-c', 'echo "✅ Flask backend setup validated in Cloud Build"']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - askdoc-backend
      - --source=.
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --project=pure-archive-460800-b6

timeout: 900s
