options:
  logging: CLOUD_LOGGING_ONLY  # Prevents the log bucket error

steps:
  # Step 1: Install dependencies
  - name: 'python:3.11'
    id: Install Dependencies
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt

  # Step 2: Run lint check (optional, can remove)
  - name: 'python:3.11'
    id: Lint Check
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Linting..."
        flake8 || echo "Lint warnings, continuing..."

  # Step 3: Print confirmation or run tests
  - name: 'python:3.11'
    id: Confirm Setup
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "✅ Flask backend setup validated in Cloud Build"

# (Optional) If you want to deploy to Cloud Run, add a deploy step below
# images:
#   - gcr.io/$PROJECT_ID/askdoc-backend
